version: "3"

services:
  fastapi:
    build:
      context: .
    command: uvicorn algotrading.main:app --reload --host 0.0.0.0
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./algotrading/:/app/algotrading
    ports:
      - 8080:8000
  tailwind:
    build:
      context: .
    volumes:
      - ./:/app
    command: tailwindcss -i ./algotrading/static/css/input.css -o ./algotrading/static/css/output.css --watch
    tty: true
