version: "3"

services:
  python:
    build:
      context: .
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./src/:/app/src
      - ./frontend:/app/frontend
    command: ["python", "/app/src/algotrading.py"]
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
