version: '3'

services:
  python:
    build:
      context: .
    env_file:
      - .env
    environment:
        - API_URL=${API_URL}
        - API_KEY=${API_KEY}
        - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./src:/app/src
    command: ["python", "/app/src/algotrading.py"]
    #command: tail -f /dev/null


