version: '3'

services:
  python:
    env_file: .env
    build:
      context: .
    environment:
        - API_URL=${API_URL}
        - API_KEY=${API_KEY}
        - API_SECRET=${API_SECRET}
    volumes:
      - ./src:/app/src
