version: "3"

services:
  fastapi:
    build:
      context: .
    command: uvicorn algotrading.main:app --reload --host 0.0.0.0
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./algotrading/:/app/algotrading
      - ./frontend:/app/frontend
    ports:
      - 8080:8000
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  tailwind:
    build:
      context: .
    volumes:
      - ./:/app
    command: tailwindcss -i ./frontend/static/css/input.css -o ./frontend/static/css/output.css --watch
    tty: true
