name: Pytest with Docker image

on: [push]
jobs:
  build:
    name: Pytest testing
    runs-on: ubuntu-latest
    container:
      image: docker://fallenmeteor/algotrading:latest
      volumes:
        - ./src/:/app/algotrading
    steps:
      - uses: actions/checkout@v4
      - name: Test with pytest
        run: |
          pytest -v
