name: Pytest with Docker image

on: [push]
jobs:
  build:
    name: Pytest in Pipenv
    runs-on: ubuntu-latest
    container:
      image: docker://${{ secrets.DOCKERHUB_USERNAME }}/algotrading:latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with pytest
        run: |
          pytest -v
